services:
  frontend:
    image: registry.audio-transcriber.ru/frontend:latest
    pull_policy: always
    container_name: frontend
    restart: unless-stopped
  backend:
    image: registry.audio-transcriber.ru/backend:latest
    pull_policy: always
    container_name: backend
    env_file:
      - .env.backend
    volumes:
      - backend_logs:/opt/app/logs
    restart: unless-stopped
  engine:
    image: registry.audio-transcriber.ru/engine:latest
    pull_policy: always
    container_name: engine
    env_file:
      - .env.engine
    volumes:
      - engine_logs:/opt/app/logs
    restart: unless-stopped

volumes:
  backend_logs:
  engine_logs:

networks:
  default:
    external: true
    name: audio-transcriber-network