services:
  nginx:
    image: nginx:1.20.1
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4.2.3-management
    container_name: rabbitmq
    restart: unless-stopped

volumes:
  registry_data:

networks:
  default:
    external: true
    name: audio-transcriber-network